# -*- coding: utf-8 -*-
"""logo

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-DLW52tVwNKUOVorTctE6Ng5KSUEDqOU
"""

import matplotlib.pyplot as plt
import numpy as np

# Define the figure and axis
fig, ax = plt.subplots()

# Circle (Blue)
circle = plt.Circle((0, 1), 0.5, color='blue', ec='black', lw=2)
ax.add_artist(circle)

# Square (Light Blue)
square = plt.Rectangle((-0.5, -0.5), 1, 1, color='lightblue', ec='black', lw=2)
ax.add_artist(square)

# Triangle (Yellow)
triangle = plt.Polygon([[-0.5, -1], [0.5, -1], [0, 0]], color='yellow', ec='black', lw=2)
ax.add_artist(triangle)

# Text ("My Logo")
ax.text(0, -1.5, 'My Logo', ha='center', va='center', fontsize=15, color='black')

# Set limits
ax.set_xlim(-1.5, 1.5)
ax.set_ylim(-2, 2)

# Aspect ratio and grid
ax.set_aspect('equal')
ax.axis('off')

# Show plot
plt.show()

from google.colab import drive
drive.mount('/content/drive')